name: My View
favicon: null
layout_spectrum: 0.22493
typography_spectrum: 0.99368
title: Life of an Aspiring Stoic
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#010005'
    - '#31395e'
    - '#fefefe'
    - '#82889f'
    - '#a6cdea'
  brandStrength: 0.5
  lightness: 0.5625
  saturation: 0.375
  rhythmicContrast: 0.25
purpose: []
