name: My View
favicon: null
layout_spectrum: 0.33063
typography_spectrum: 0.99368
title: Life of an Aspiring Stoic
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#fdfdfd'
    - '#313131'
    - '#cfcfcf'
    - '#111111'
    - '#868686'
  brandStrength: 0.5
  lightness: 0.625
  saturation: 0.5625
  rhythmicContrast: 0
purpose: []
