name: My View
favicon: null
layout_spectrum: 0.59992
typography_spectrum: 0.71887
title: Life of an Aspiring Stoic
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#1c2125'
    - '#a2b3a9'
    - '#728b88'
    - '#374143'
    - '#505a5c'
  brandStrength: 0.5
  lightness: 0.6875
  saturation: 0
  rhythmicContrast: 0.25
purpose: []
