name: My View
favicon: null
layout_spectrum: 0.33063
typography_spectrum: 0.99368
title: Life of an Aspiring Stoic
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#5e5c4a'
    - '#f2e76d'
    - '#928b6d'
    - '#2c322c'
    - '#0a100f'
  brandStrength: 0.5
  lightness: 0.5
  saturation: 1
  rhythmicContrast: 1
purpose: []
