name: My View
favicon: null
layout_spectrum: 0.35601
typography_spectrum: 0.72971
title: Life of an Aspiring Stoic
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#d3d8de'
    - '#bec1c8'
    - '#828f98'
    - '#030d17'
    - '#33535e'
  brandStrength: 0.5
  lightness: 0.9375
  saturation: 0.5
  rhythmicContrast: 1
purpose: []
