name: My View
favicon: null
layout_spectrum: 0.19964
typography_spectrum: 0.99368
title: Life of an Aspiring Stoic
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000501'
    - '#d0cfd5'
    - '#9da1aa'
    - '#fff9fd'
    - '#757f8b'
  brandStrength: 0.5
  lightness: 0.5625
  saturation: 0.0625
  rhythmicContrast: 0
purpose: []
